# Generated by Django 5.1.3 on 2024-11-29 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_system_database', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityarea',
            name='room_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ReservationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('activity_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_system_database.activityarea')),
                ('reserve_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activity_area', 'reserve_user', 'date')},
            },
        ),
    ]
