# Generated by Django 5.1.3 on 2024-11-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_system_database', '0005_communityannouncement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityannouncement',
            old_name='announcment_id',
            new_name='announcement_id',
        ),
    ]
