# Generated by Django 5.1.3 on 2024-11-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_system_database', '0007_teach'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teaches',
        ),
    ]
